<a href="https://colab.research.google.com/github/touhid0503/Pandas/blob/main/pandas_26_01_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

#Indexing

In [3]:
A=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
A

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [5]:
A['a':'c']

a    1
b    2
c    3
dtype: int64

In [7]:
A[0:3]

a    1
b    2
c    3
dtype: int64

In [11]:
B=pd.Series(['A','B','D',],index=[1,3,4])
B

1    A
3    B
4    D
dtype: object

In [12]:
B[1]

'A'

In [20]:
B[1:3] #implicit

3    B
4    D
dtype: object

In [22]:
B.loc[1:3] #explicit

1    A
3    B
dtype: object

In [17]:
B.iloc[1:3] #implicit

3    B
4    D
dtype: object

In [27]:
B.iloc[:-1]

1    A
3    B
dtype: object

In [36]:
Area=pd.Series({'California':423967,'Texas':695662,'New York':141297,'Florida':170312,'Illinois':149995})
Pop=pd.Series({'California':38332521,'Texas':26448193,'New York':19651127,'Florida':19552860,'Illinois':12882135})

In [42]:
C=pd.DataFrame({'area':Area,'pop':Pop},index=['California','Texas','New York','Florida','Illinois'])
C

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [43]:
C.iloc[2,:]

area      141297
pop     19651127
Name: New York, dtype: int64

In [45]:
C.loc['California',:]

area      423967
pop     38332521
Name: California, dtype: int64

In [46]:
C.loc[:,'area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [47]:
C.loc[::-1,:]

              area       pop
Illinois    149995  12882135
Florida     170312  19552860
New York    141297  19651127
Texas       695662  26448193
California  423967  38332521

In [48]:
C.loc[:,::-1]

                 pop    area
California  38332521  423967
Texas       26448193  695662
New York    19651127  141297
Florida     19552860  170312
Illinois    12882135  149995

#csv files

In [73]:
from sklearn.impute import SimpleImputer

In [74]:
df=pd.read_csv('/content/mushrooms.csv')
df

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,e,k,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,b,c,l
8120,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,n,o,p,b,v,l
8121,e,f,s,n,f,n,a,c,b,n,...,s,o,o,p,o,o,p,b,c,l
8122,p,k,y,n,f,y,f,c,n,b,...,k,w,w,p,w,o,e,w,v,l
8123,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,o,c,l

In [75]:
df.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

In [76]:
df.drop(['class','cap-shape'],inplace=True,axis=1)

In [77]:
df.head(5)

,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,stalk-shape,stalk-root,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,s,n,t,p,f,c,n,k,e,e,...,s,w,w,p,w,o,p,k,s,u
1,s,y,t,a,f,c,b,k,e,c,...,s,w,w,p,w,o,p,n,n,g
2,s,w,t,l,f,c,b,n,e,c,...,s,w,w,p,w,o,p,n,n,m
3,y,w,t,p,f,c,n,n,e,e,...,s,w,w,p,w,o,p,k,s,u
4,s,g,f,n,f,w,b,k,t,e,...,s,w,w,p,w,o,e,n,a,g

In [78]:
df.rename(columns={'cap-surface':'cap_surface','gill-attachment':'gill_attachment'},inplace=True)

In [79]:
df.head(5)

,cap_surface,cap-color,bruises,odor,gill_attachment,gill-spacing,gill-size,gill-color,stalk-shape,stalk-root,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,s,n,t,p,f,c,n,k,e,e,...,s,w,w,p,w,o,p,k,s,u
1,s,y,t,a,f,c,b,k,e,c,...,s,w,w,p,w,o,p,n,n,g
2,s,w,t,l,f,c,b,n,e,c,...,s,w,w,p,w,o,p,n,n,m
3,y,w,t,p,f,c,n,n,e,e,...,s,w,w,p,w,o,p,k,s,u
4,s,g,f,n,f,w,b,k,t,e,...,s,w,w,p,w,o,e,n,a,g

In [80]:
#df['Date']=pd.to_datetime(df['Date'])

In [81]:
df.describe()

,cap_surface,cap-color,bruises,odor,gill_attachment,gill-spacing,gill-size,gill-color,stalk-shape,stalk-root,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
count,8124,8124,8124,8124,8124,8124,8124,8124,8124,8124,...,8124,8124,8124,8124,8124,8124,8124,8124,8124,8124
unique,4,10,2,9,2,2,2,12,2,5,...,4,9,9,1,4,3,5,9,6,7
top,y,n,f,n,f,c,b,b,t,b,...,s,w,w,p,w,o,p,w,v,d
freq,3244,2284,4748,3528,7914,6812,5612,1728,4608,3776,...,4936,4464,4384,8124,7924,7488,3968,2388,4040,3148

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   cap_surface               8124 non-null   object
 1   cap-color                 8124 non-null   object
 2   bruises                   8124 non-null   object
 3   odor                      8124 non-null   object
 4   gill_attachment           8124 non-null   object
 5   gill-spacing              8124 non-null   object
 6   gill-size                 8124 non-null   object
 7   gill-color                8124 non-null   object
 8   stalk-shape               8124 non-null   object
 9   stalk-root                8124 non-null   object
 10  stalk-surface-above-ring  8124 non-null   object
 11  stalk-surface-below-ring  8124 non-null   object
 12  stalk-color-above-ring    8124 non-null   object
 13  stalk-color-below-ring    8124 non-null   object
 14  veil-type                 8124 non-null   object
 15  veil-color                8124 non-null   object
 16  ring-number               8124 non-null   object
 17  ring-type                 8124 non-null   object
 18  spore-print-color         8124 non-null   object
 19  population                8124 non-null   object
 20  habitat                   8124 non-null   object
dtypes: object(21)
memory usage: 1.3+ MB

In [83]:
df.isnull().sum()

cap_surface                 0
cap-color                   0
bruises                     0
odor                        0
gill_attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [84]:
#df.fillna(0,inplace=True)

In [86]:
df.shape

(8124, 21)

In [87]:
df.duplicated().sum()

np.int64(4428)

In [88]:
df.drop_duplicates(inplace=True)

In [89]:
df.shape

(3696, 21)

In [106]:
#df2=df.groupby('gill_attachment')[['population','habitat']].sum().reset_index()

In [110]:
#df3=df[df['gill_attachment']<1000]