<a href="https://colab.research.google.com/github/touhid0503/Pandas/blob/main/pandas_25_01_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#library

In [2]:
import pandas as pd

In [3]:
pd.__version__

'2.2.2'

#Series

In [4]:
A=pd.Series([1,2,3,4],index=['a',1,'c','ee'])
A

a     1
1     2
c     3
ee    4
dtype: int64

In [5]:
print(A)

a     1
1     2
c     3
ee    4
dtype: int64

In [6]:
A.ndim

1

In [7]:
A.dtype

dtype('int64')

In [8]:
A.nbytes

32

In [9]:
print(type(A))

<class 'pandas.core.series.Series'>

In [10]:
A.values

array([1, 2, 3, 4])

In [11]:
A.index

Index(['a', 1, 'c', 'ee'], dtype='object')

In [12]:
type(A.values)

numpy.ndarray

In [13]:
print(A['ee'])

4

In [14]:
A['a':'c']

a    1
1    2
c    3
dtype: int64

In [15]:
A['a':]

a     1
1     2
c     3
ee    4
dtype: int64

In [16]:
A[:'c']

a    1
1    2
c    3
dtype: int64

In [17]:
grads=pd.Series({'A':4,'B':3.5,'C':3,'D':2.5})

In [18]:
grads.values

array([4. , 3.5, 3. , 2.5])

In [19]:
grads.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [20]:
marks=pd.Series({'A':85,'B':75,'C':65,'D':55})

In [21]:
marks.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [22]:
marks.values

array([85, 75, 65, 55])

In [23]:
type(marks)

pandas.core.series.Series

In [24]:
type(marks.values)

numpy.ndarray

In [25]:
marks.dtype

dtype('int64')

In [26]:
marks.ndim

1

In [27]:
marks.nbytes

32

In [28]:
marks

A    85
B    75
C    65
D    55
dtype: int64

In [29]:
marks['B']

np.int64(75)

In [30]:
marks[0:2]

A    85
B    75
dtype: int64

In [31]:
marks[:2]

A    85
B    75
dtype: int64

In [32]:
marks[2:]

C    65
D    55
dtype: int64

In [33]:
marks[:-1]

A    85
B    75
C    65
dtype: int64

In [34]:
marks[-1:]

D    55
dtype: int64

#DataFrame

In [35]:
B=pd.DataFrame({'Marks':marks,'Grades':grads})

In [36]:
B

   Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [37]:
B.T

           A     B     C     D
Marks   85.0  75.0  65.0  55.0
Grades   4.0   3.5   3.0   2.5

#values

In [38]:
B.values

array([[85. ,  4. ],
       [75. ,  3.5],
       [65. ,  3. ],
       [55. ,  2.5]])

In [39]:
B.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [40]:
print(type(B))
print(type(B.values))
print(type(B.values[1]))
print(type(B.values[0][0]))
print(type(B.values[0][1]))
print(B.values[0][0])
print(B.values[1][0])
print(B.values[0][1])
print(B.ndim)
print(B.Grades)
print(B.Marks)

<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>
<class 'numpy.float64'>
85.0
75.0
4.0
2
A    4.0
B    3.5
C    3.0
D    2.5
Name: Grades, dtype: float64
A    85
B    75
C    65
D    55
Name: Marks, dtype: int64

In [41]:
print(B.dtypes)

Marks       int64
Grades    float64
dtype: object

In [44]:
B.values[2,1]

np.float64(3.0)

In [49]:
B.index[0]

'A'

In [50]:
B.values[0]

array([85.,  4.])

In [51]:
B.columns

Index(['Marks', 'Grades'], dtype='object')

In [53]:
B.columns[1]

'Grades'

In [54]:
B.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [56]:
B.values[1:]

array([[75. ,  3.5],
       [65. ,  3. ],
       [55. ,  2.5]])

In [58]:
B.values[:2]

array([[85. ,  4. ],
       [75. ,  3.5]])

In [59]:
B.values[:,1]

array([4. , 3.5, 3. , 2.5])

In [60]:
B.values[1,:]

array([75. ,  3.5])

In [61]:
B.values[:-1]

array([[85. ,  4. ],
       [75. ,  3.5],
       [65. ,  3. ]])

In [62]:
B.values[-1:]

array([[55. ,  2.5]])

In [63]:
B.values[1:3,1]

array([3.5, 3. ])

In [64]:
B['scalemarks']=100*(B['Marks']/90)

In [65]:
B

   Marks  Grades  scalemarks
A     85     4.0   94.444444
B     75     3.5   83.333333
C     65     3.0   72.222222
D     55     2.5   61.111111

In [66]:
del B['scalemarks']

In [67]:
B

   Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [68]:
B[B['Marks']>70]

   Marks  Grades
A     85     4.0
B     75     3.5

In [69]:
B['Marks']>70

A     True
B     True
C    False
D    False
Name: Marks, dtype: bool

#NaN

In [84]:
A=pd.DataFrame([{'a':1,'b':4},{'b':-3,'c':9}])

In [85]:
A

     a  b    c
0  1.0  4  NaN
1  NaN -3  9.0

In [86]:
A.fillna(0)

     a  b    c
0  1.0  4  0.0
1  0.0 -3  9.0

In [87]:
A.dropna?

In [88]:
A

     a  b    c
0  1.0  4  NaN
1  NaN -3  9.0