<a href="https://colab.research.google.com/github/touhid0503/Pandas/blob/main/pandas_03_02_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Example DataFrame

In [1]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'Country': ['USA', 'Canada', 'UK']
}

df = pd.DataFrame(data)
print(df)

      Name  Age Country
0    Alice   25     USA
1      Bob   30  Canada
2  Charlie   35      UK

#Loading a DataFrame

In [2]:
#df = pd.read_csv('data.csv')        # Load from CSV
#df = pd.read_excel('data.xlsx')     # Load from Excel
#df = pd.DataFrame(data_dict)        # Load from dictionary

#Exploring a DataFrame

In [4]:
df.head()        # First 5 rows

      Name  Age Country
0    Alice   25     USA
1      Bob   30  Canada
2  Charlie   35      UK

In [5]:
df.tail()        # Last 5 rows

      Name  Age Country
0    Alice   25     USA
1      Bob   30  Canada
2  Charlie   35      UK

In [6]:
df.info()        # Column types and non-null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     3 non-null      object
 1   Age      3 non-null      int64
 2   Country  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [7]:
df.describe()    # Summary stats

        Age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0

In [8]:
df.columns       # Column names

Index(['Name', 'Age', 'Country'], dtype='object')

In [9]:
df.index         # Row indices

RangeIndex(start=0, stop=3, step=1)

In [10]:
df.values

array([['Alice', 25, 'USA'],
       ['Bob', 30, 'Canada'],
       ['Charlie', 35, 'UK']], dtype=object)

In [11]:
df.ndim

2

In [12]:
df.dtypes

Name       object
Age         int64
Country    object
dtype: object

In [13]:
df.shape

(3, 3)

In [15]:
type(df)

pandas.core.frame.DataFrame

In [16]:
type(df.values)

numpy.ndarray

#Accessing & Filtering Data

Basic Access

In [23]:
df['Age']                  # Single column

0    25
1    30
2    35
Name: Age, dtype: int64

In [24]:
df[['Name', 'Age']]        # Multiple columns

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [25]:
df.iloc[0]                 # First row by position

Name       Alice
Age           25
Country      USA
Name: 0, dtype: object

In [26]:
df.loc[0]                  # First row by label

Name       Alice
Age           25
Country      USA
Name: 0, dtype: object

Conditional Filtering (Boolean masks)

In [27]:
df[df['Age'] > 30]                          # Age over 30

      Name  Age Country
2  Charlie   35      UK

In [28]:
df[df['Country'] == 'USA']                 # Country match

    Name  Age Country
0  Alice   25     USA

In [29]:
df[(df['Age'] > 25) & (df['Country'] == 'UK')]  # Multiple conditions

      Name  Age Country
2  Charlie   35      UK

Advanced Filtering

In [30]:
df[df['Name'].str.startswith('A')]         # Names starting with A

    Name  Age Country
0  Alice   25     USA

In [31]:
df[df['Country'].isin(['USA', 'UK'])]      # Match multiple values

      Name  Age Country
0    Alice   25     USA
2  Charlie   35      UK

In [32]:
df[~df['Country'].isin(['Canada'])]        # NOT condition

      Name  Age Country
0    Alice   25     USA
2  Charlie   35      UK

#CRUD Operations in Pandas

Create (Insert Rows)

In [34]:
new_row = pd.DataFrame([{'Name': 'Diana', 'Age': 28, 'Country': 'Germany'}])
df = pd.concat([df, new_row], ignore_index=True)

In [35]:
df

      Name  Age  Country
0    Alice   25      USA
1      Bob   30   Canada
2  Charlie   35       UK
3    Diana   28  Germany

Read (Access Data)

In [36]:
df.loc[df['Name'] == 'Alice']

    Name  Age Country
0  Alice   25     USA

In [37]:
df.iloc[2]

Name       Charlie
Age             35
Country         UK
Name: 2, dtype: object

Update (Modify Values)

In [38]:
df.loc[df['Name'] == 'Bob', 'Age'] = 31             # Update Bob's age
df['Country'] = df['Country'].str.upper()           # Convert all country names to uppercase

In [39]:
df

      Name  Age  Country
0    Alice   25      USA
1      Bob   31   CANADA
2  Charlie   35       UK
3    Diana   28  GERMANY

 Delete (Drop Data)

In [40]:
df = df.drop(2, axis=0)                             # Drop row with index 2
df = df[df['Name'] != 'Alice']                      # Drop rows where name == Alice
df = df.drop('Age', axis=1)                         # Drop 'Age' column

In [41]:
df

    Name  Country
1    Bob   CANADA
3  Diana  GERMANY

#Cleaning Data

In [47]:
df.isnull().sum()                          # Count missing values

Name       0
Country    0
dtype: int64

In [48]:
#df.dropna(inplace=True)                   # Drop rows with missing values

In [49]:
#df.fillna({'Age': 0}, inplace=True)       # Fill missing Age values with 0

In [50]:
#df.isnull().sum()

In [53]:
df.rename(columns={'Name': 'name'}, inplace=True)   # Rename column

In [54]:
df

    name  Country
1    Bob   CANADA
3  Diana  GERMANY

In [58]:
df['name'] = df['name'].astype(object)   # Convert column to float

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, 1 to 3
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     2 non-null      object
 1   Country  2 non-null      object
dtypes: object(2)
memory usage: 48.0+ bytes

#Analyzing Data

In [60]:
df['Country'].value_counts()                       # Count occurrences

Country
CANADA     1
GERMANY    1
Name: count, dtype: int64

In [64]:
#df.groupby('Country')['Age'].mean()                # Average age per country

In [66]:
df.sort_values(by='name', ascending=False)          # Sort by name descending

    name  Country
3  Diana  GERMANY
1    Bob   CANADA

#Saving Data

In [67]:
#df.to_csv('cleaned_data.csv', index=False)
#df.to_excel('output.xlsx', index=False)